# Generated by Django 5.2.6 on 2025-09-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_aboutpage_options_remove_aboutpage_image_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='about',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
