# Generated by Django 5.2.6 on 2025-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_skill_about_delete_project_delete_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveSmallIntegerField(default=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Intro paragraph (markdown/plain text)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/profile/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='about_pages', to='pages.skill')),
            ],
        ),
    ]
