# Generated by Django 5.2.6 on 2025-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_skill_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_range', models.CharField(blank=True, max_length=80)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_range', models.CharField(blank=True, max_length=80)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('bullets', models.TextField(blank=True, help_text='Use newline-separated bullets. They will be rendered as list items.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Short intro shown above resume sections.')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('education', models.ManyToManyField(blank=True, related_name='resume_pages', to='pages.education')),
                ('experience', models.ManyToManyField(blank=True, related_name='resume_pages', to='pages.experience')),
            ],
            options={
                'verbose_name': 'Resume Page',
                'verbose_name_plural': 'Resume Pages',
            },
        ),
    ]
