# Generated by Django 5.2.6 on 2025-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_education_experience_resumepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ecommerce', 'E-Commerce'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('productivity', 'Productivity Tools'), ('other', 'Other')], default='other', max_length=30)),
                ('tools', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'order', '-created'],
            },
        ),
    ]
